### ISSUE TITLE
VirtualBox can be blocked by HyperV

### ISSUE THREAD

**Issue by KernelFrog** [rdbreak/rhce8env#1]
Running the 'vagrant up' environment build will fail If HyperV is installed on the Windows VirtualBox host.  
Error is usually "VT-x is not available. (VERR_VMX_NO_VMX)" or similar, when the script attempts to boot the first VM.

Resolution seems to be either remove HyperV, or  preventing its hypervisor from starting with the command:
bcdedit /set hypervisorlaunchtype off

followed by a reboot.

Suggest a documentation update to mention this for the practice environments.

**Comment by rdbreak** [comment]
I'll add a "known issues" section to the next push. Thanks!
