### ISSUE TITLE
Vagrant doesn't support Virtualbox 6.1 yet. (Mac)

### ISSUE THREAD

**Issue by Oddly** [rdbreak/rhce8env#2]
Installing with the command
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && xcode-select --install &&brew install ansible ; brew install python ; brew cask install vagrant ; brew cask install VirtualBox ; brew cask install virtualbox-extension-pack ; vagrant plugin install vagrant-guest_ansible`
works, it installs Virtualbox 6.1, but this is not yet supported by the version provided by Brew.
A solution is to pach Vagrant with [these](https://github.com/hashicorp/vagrant/issues/11249#issuecomment-565736894) commands, or use the official Vagrant packages instead of the Brew cask ones.

**Comment by Oddly** [comment]
A side note, The shared folder doesn't work either, because the Virtualbox guest additions isn't version 6.1 yet. 6.1 adds shared folder functionality for Mac.

**Comment by jorp** [comment]
I can confirm the same on Fedora 31.
```
$ vagrant up --provider=virtualbox
The provider 'virtualbox' that was requested to back the machine 'repo' is reporting that it isn't usable on this system. The reason is shown below:
Vagrant has detected that you have a version of VirtualBox installed that is not supported by this version of Vagrant. 
Please install one of the supported versions listed below to use Vagrant:
4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0
A Vagrant update may also be available that adds support for the version you specified. Please check www.vagrantup.com/downloads.html to download the latest version.
```
I had success with installing the last 6.0.x release (6.0.14) of VirtualBox found [here](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0).

**Comment by rdbreak** [comment]
Confirmed Virtualbox 6.0 is set in the installation script.
