### ISSUE TITLE
Virtualbox guest additions is outdated on the images.

### ISSUE THREAD

**Issue by Oddly** [rdbreak/rhce8env#5]
Maybe use a Ansible role to update the guest additions to the latest version automatically. This would resolve the shared folder on Mac not working.
For example:
https://github.com/PeterMosmans/ansible-role-virtualbox-guest

**Comment by rdbreak** [comment]
I experimented with guest additions at the beginning of development and it caused more problems than it fixed. I'll give it another look soon though. Thanks!

**Comment by Oddly** [comment]
Alright. I only brought it up because I saw that the guest additions were already installed, it complained about it being another version than the virtualbox version installed on my Mac.
It's not needed for me, maybe a nice to have for when you have time.
