### ISSUE TITLE
Rpm repositories issues

### ISSUE THREAD

**Issue by mossroy** [rdbreak/rhce8env#8]
Hi,

yesterday I've set up this environment with vagrant to do the practice exam.

First of all, many thanks for preparing and maintaining this. It is very valuable to be able to train with a practice exam.

But I had several issues related to the yum repositories : 

- ~~The repo VM is working fine and exposes the BaseOS and AppStream repositories through HTTP. But they does not seem to contain some necessary packages for the practice exam : at least mod_ssl and php (for task 10), haproxy (for task 11), and PyMySQL (for the mysql_user ansible module for task 9). Or maybe I missed something?~~
- The repo VM does not expose the MySQL repo that we have to configure on task 8. http://repo.example.com/rpms gives a 404 error response
- Maybe it's on purpose but I was surprised that no repo was configured at all. That gives no template to create .repo files in /etc/yum.repos.d
- I tried to install ansible through the repo VM but it was not available in it. I finally discovered that it was already installed, which is confusing because the first task is to install it. Maybe it would be worth mentioning that more clearly in the practice exam?
- The man pages of ansible command-lines are missing. These command-lines can be called with `--help`, which gives the main information, but the man pages give much more detail

**Comment by rdbreak** [comment]
All RPMs available with RHEL 8 are available from the repo server. I copied the RPMs from the RHEL 8 install media. Repos are available but the respective repo files need to be created to access the repos which is normal for an exam environment. Ansible is already installed in the environment (needed for environment configuration) and can be checked by typing `ansible --version`. Lastly, I'm able to ansible the ansible help and ansible docs. Can you upload a screenshot of you having these issues?

**Comment by mossroy** [comment]
Thanks for this feedback.
Here is a screenshot about RPMs on the repo server : 
![image](https://user-images.githubusercontent.com/890923/72504717-a6747800-383e-11ea-8e53-b778eae2bbcb.png)
And another one about the missing man pages on the control server (where Ansible is preinstalled) : 
![image](https://user-images.githubusercontent.com/890923/72504923-200c6600-383f-11ea-8c10-3938788c1d91.png)

But I understood what I did wrong about the packages : I had only configured the BaseOS repo. The packages I mentioned are in AppStream.
So please forget the first problem of my list, my bad.

NB : I created these VMs on an Ubuntu 18.04 host, using Vagrant 2.2.6 and VitrualBox 6.0. But I did not install the snap for ruby, because it was already installed on my machine, with version 2.5.1p57

**Comment by rdbreak** [comment]
> The repo VM does not expose the MySQL repo that we have to configure on task 8.

The practice exam has been adjusted.

> Maybe it's on purpose but I was surprised that no repo was configured at all. That gives no template to create .repo files in /etc/yum.repos.d

This is on purpose.

> I tried to install ansible through the repo VM but it was not available in it. I finally discovered that it was already installed, which is confusing because the first task is to install it. Maybe it would be worth mentioning that more clearly in the practice exam?

Added this to the practice exam.

> The man pages of ansible command-lines are missing. These command-lines can be called with --help, which gives the main information, but the man pages give much more detail

The method in which Ansible is installed (pip) is the reason for this, the man pages aren't included in the python library. Until this is fixed, you can use `ansible-doc <module name>` for the time being.

**Comment by lucky01001** [comment]
could you fix the path to the repos in task 8? its still "repo.example.com" where it should be "repo.ansi.example.com"

**Comment by rdbreak** [comment]
This has been changed.
